version: "3"
services:
    app:
        build: python
        volumes:
            - "./study_englishword_app:/home/workspace/app/study_englishword_app"
        ports:
            - "8000:8000"
        tty: true
        links:
            - mariadb

    mariadb:
        image: mariadb:latest
        ports:
            - "3306:3306"
        volumes:
            - "./database/mysql-data:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: root
            TZ: 'Asia/Tokyo'
