version: "3"
services:
    app:
        build: python
        volumes:
            - "./app:/app"
        ports:
            - "8000:8000"
        environment:
            MYSQL_DATABASE: english_app_db
            MYSQL_USER: django
            MYSQL_PASSWORD: django
            MYSQL_HOSTNAME: mariadb
        tty: true
        depends_on:
            - mariadb

    mariadb:
        image: mariadb:latest
        ports:
            - "3306:3306"
        volumes:
            - "./database/mysql-data:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: english_app_db
            MYSQL_USER: django
            MYSQL_PASSWORD: django
            TZ: 'Asia/Tokyo'
