# Generated by Django 2.1.2 on 2019-08-15 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='半角英字のみ単語登録可能です', regex='^[a-zA-Z]+$')])),
                ('mean1', models.CharField(max_length=100)),
                ('mean2', models.CharField(default='', max_length=100, null=True)),
                ('mean3', models.CharField(default='', max_length=100, null=True)),
                ('part_of_speech', models.PositiveSmallIntegerField()),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('logical_delete_flag', models.BooleanField(default=False)),
            ],
        ),
    ]
